---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
             driverClassName: com.mysql.jdbc.Driver
             pooled: true
             username: root
             zeroDateTimeBehavior: convertToNull
             password: password
             dbCreate: update
             dialect: org.hibernate.dialect.MySQL5InnoDBDialect
             url: jdbc:mysql://localhost/ikariera?autoreconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull

    test:
        dataSource:
              driverClassName: com.mysql.jdbc.Driver
              pooled: true
              username: root
              zeroDateTimeBehavior: convertToNull
              password: password
              dbCreate: create-drop
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect
              url: jdbc:mysql://localhost/ikariera?autoreconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull

    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 10 * 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState;StatementCache(max=200)
                defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED

---

